 name: MCDuel
 main: com.kickass.MCDuel.MCDuel
 authors: [BR3TON, Rza1337]
 version: 0.1.2
 commands:
   duel:
      description: Duel command.
      usage: /duel [player]
 permissions:
   mcduel.duel:
     description: Gives access to duel command