 name: MCDuel
 main: com.kickass.MCDuel
 authors: [BR3TON, Rza1337]
 version: 0.0.1
 commands:
   duel:
      description: Duel command.
      usage: /duel [player]
 permissions:
   bannaduel.duel:
     description: Gives access to duel command